apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation
  labels:
    app: donation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donation
  template:
    metadata:
      labels:
        app: donation
    spec:
      containers:
        - name: donation
          image: 496278789073.dkr.ecr.ap-northeast-2.amazonaws.com/skccuser08-donation:f79b14cc6467d4f05b9bbc6aeecffb2f1d964522
          resources:
            requests:
              cpu: "300m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: moviecm
                  key: text1