apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation
  labels:
    app: donation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donation
  template:
    metadata:
      labels:
        app: donation
    spec:
      containers:
        - name: donation
          image: username/donation:latest
          ports:
            - containerPort: 8080
          env:
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: moviecm
                  key: text1