apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  namespace: movie
  labels:
    app: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: 496278789073.dkr.ecr.ap-northeast-2.amazonaws.com/skteam03-book:v11
          ports:
            - containerPort: 8080
          env:
            - name: LANGUAGE
              valueFrom:
                configMapKeyRef:
                  name: hello-cm
                  key: language